---
apiVersion: v1
kind: Service
metadata:
  name: appname
  labels:
    app: appname
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: appname